<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base_link" params="base_size">

    <xacro:property name="base_size_z" value="${float(base_size.split()[2])}"/>

    <link name="base_footprint" />

    <link name="base_link">
      <visual>
        <geometry>
          <box size="${base_size}"/>
        </geometry>
        <origin xyz="0 0 ${base_size_z / 2}"/>
        <material name="blue">
          <color rgba="${color_blue}"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${base_size}"/>
        </geometry>
        <origin xyz="0 0 ${base_size_z / 2}"/>
        <material name="blue">
          <color rgba="${color_blue}"/>
        </material>
      </collision>
      <inertial>
        <origin xyz="0 0 ${base_size_z / 2}" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia
          ixx="0.1" ixy="0.0" ixz="0.0"
          iyy="0.1" iyz="0.0"
          izz="0.1"/>
      </inertial>
    </link>

    <joint name="joint_name" type="fixed">
      <origin xyz="0 0 ${base_size_z + 0.05}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

  </xacro:macro>
</robot>
